CREATE TABLE `profile` (
	`No` INT(11) NOT NULL AUTO_INCREMENT,
	`이름` VARCHAR(50) NULL DEFAULT NULL,
	`데뷔` VARCHAR(50) NULL DEFAULT NULL,
	`출생` VARCHAR(50) NULL DEFAULT NULL,
	`포지션` VARCHAR(50) NULL DEFAULT NULL,
	`신체` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`No`)
)
COMMENT='나성범의 프로필'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=8
;
